version: "3"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: my-node-app
    ports:
      - 3333:3333
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://admin:admin@database:5432/database
    volumes:
      - ./api:/app

  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: my-react-app
    ports:
      - 3000:3000
    volumes:
      - ./public:/app

volumes:
  pgdata:
    driver: local
